name: tests
on:
  pull_request:
    types: [ opened, synchronize ]
  push:
    branches:
      - main
      - master
      - staging
      - qa
      - development

env:
  CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
  SONAR_PROJECT: ${{ secrets.SONAR_PROJECT }}
  SONAR_URL: ${{ secrets.SONAR_URL }}
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # This needs to match Node version in package.json
      - uses: actions/setup-node@v1
        with:
          node-version: '^14.5.0'

      - name: Install Dependencies
        run: yarn

      - name: Run Tests
        run: yarn test:cover
      
      - name: Setup Code Climate test reporter
        run: |
          pwd
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
          chmod +x ./cc-test-reporter
          ./cc-test-reporter before-build
          ./cc-test-reporter after-build -t lcov

      - name: Setup sonar scanner
        uses: warchant/setup-sonar-scanner@v3

      - name: Run Sonarqube analysis
        run: |
          sonar-scanner \
            -Dsonar.qualitygate.wait=true \
            -Dsonar.host.url=$SONAR_URL \
            -Dsonar.login=$SONAR_TOKEN \
            -Dsonar.projectKey=$SONAR_PROJECT \
            -Dsonar.scm.provider=git \
            -Dsonar.java.binaries=/tmp \
            -Dsonar.nodejs.executable=$(which node) \
            -Dsonar.projectVersion=$(echo $GITHUB_SHA | cut -c1-8) \
            -Dsonar.sourceEncoding=UTF-8 \
            -Dsonar.sources=src \
            -Dsonar.tests=__tests__ \
            -Dsonar.projectBaseDir=. \
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info \
            -Dsonar.exclusions=**/rnb-cli/** \
            -Dsonar.coverage.exclusions=**/spec.js,__mocks__/**/*.*,__tests__/**/*.*,**/**.spec.js,**/**.config.js,**/rnbv.js,android/**/*.*,ios/**/*.*,**/**.styles.js,**/tests/**/*.*,**/__mocks__/**/*.*,**/jest-setup.js,**/constants/**,**/assets/**,node_modules/**/*.*,coverage/**/*.*,rnb-cli/**/*.*,**/src/**/*.*,**.config.js
